name: CIBT Python Build
description: CIBT Composite Actions to build Python Project

inputs:
  srcDir:
    description: "source directory path (default: ./src/Apis)"
    required: false
    default: "./src/Apis"
  version:
    description: python version (3.8.x)
    required: false
    default: 3.8.x
  testDir:
    description: Test directory path 
    required: false
    default: "./test"
  unitTest:
    description: run unit test (true|false)
    required: false
    default: "true"
  codeCoverage:
    description: run code coverage (true|false)
    required: false
    default: "false"
outputs:
  test_reports:
    description: "Test Report"
    value: ${{ steps.unit_tests.outputs.test_reports }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.version }}
        
      - name: Install dependencies
        run: |
          cd ${{ inputs.srcDir }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build
        shell: bash
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true
        shell: bash
      - name: Test with pytest
        run: |
          pip install pytest
          export PYTHONPATH=src
          pytest


    - name: Run Code Coverage
      run: |
        if [[ "${{inputs.codeCoverage}}" == "true" ]]; then
          pip install pytest-cov
          pytest --cov src
        fi
      shell: bash
