name: CIBT Python Build
description: CIBT Composite Actions to build Python Project

inputs:
  srcDir:
    description: "source directory path (default: ./src/Apis)"
    required: false
    default: "./src/Apis"
  version:
    description: python version (3.8.x)
    required: false
    default: 3.8.x
  testDir:
    description: Test directory path 
    required: false
    default: "./test"
  unitTest:
    description: run unit test (true|false)
    required: false
    default: "true"
  codeCoverage:
    description: run code coverage (true|false)
    required: false
    default: "false"
outputs:
  test_reports:
    description: "Test Report"
    value: ${{ steps.unit_tests.outputs.test_reports }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
    - name: Lint with flake8
      run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash
      
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest
