name: 'build, test'
description: 'composite actions'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2.1.0
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        shell: bash
      - name: Test with pytest
        run: |
          pip install pytest
          export PYTHONPATH=src
          pytest
        shell: bash
