name: 'build, test'
description: 'composite actions'
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2.1.0
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build
        shell: bash
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true
        shell: bash
      - name: Test with pytest
        run: |
          pip install pytest
          export PYTHONPATH=src
          pytest
        shell: bash
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest
        shell: bash
